### ISSUE TITLE
How to empty failed registry of given queue?

### ISSUE THREAD

**Issue by nikkonrom** [Parallels/rq-dashboard#271]
I'm using the newest version of RQ dashboard from GitHub repo (cause it has very useful feature of displaying all registers of all queues unlike version from PyPi). But in comparison with previous version, this does not have a button to empty fail jobs from queue, despite of this button exists in queued registry:
![Screenshot from 2019-11-20 18-04-01](https://user-images.githubusercontent.com/22215769/69250959-aac74080-0bc1-11ea-98f5-244331f0ecc3.png)
![Screenshot from 2019-11-20 18-04-41](https://user-images.githubusercontent.com/22215769/69250978-b450a880-0bc1-11ea-937a-30351d72c395.png)
How to enable this functionality or perform this action in other way?

**Comment by coolhacker** [comment]
The master version has not yet been completed, so some functionality is still inactive. In legacy branch this functionality works because of slightly different failed registry processing, and it will certainly be on version 1.0 release.  (Actually earlier, I will close this issue when it is resolved).  Thanks for the feedback!

**Comment by eoranged** [comment]
Beware that master branch is currently actively developed and potentially can be very unstable and break things badly. Also UI, configuration format, API and code can change significantly overnight.
If you need any kind of stability, please prefer sticking to releases.
