### ISSUE TITLE
Show completed jobs and possibily inspect results

### ISSUE THREAD

**Issue by davibe** [Parallels/rq-dashboard#69]
Would it be possible ? Any ETA on this ?

**Comment by nvie** [comment]
Yes, it would be possible. And nope, no ETAs.

Put differently: I don't have the time to work on this. If you want it, go ahead and implement it. Then submit a PR for review if you think others will benefit from it. If it's readable, maintainable, and useful, I'll pull it. This is the world of open source :)

Now, any ETA on that pull request? ;)

**Comment by davibe** [comment]
No ETA on my pull request of course, but i will take a look.
Sorry if I sounded pretentious, I just wanted to check you were not doing
it already before diving in.

**Comment by nvie** [comment]
Not a problem :) I'm not working on it, but do look forward to a contribution. Thanks :)

**Comment by ducu** [comment]
Anyone else working on this? @davibe ?
It would be nice to see the latest results per queue indeed. I'm willing to contribute, or start a new fork if nobody else started it yet.

**Comment by davibe** [comment]
I did not start yet and i'm not going to before Feb so you can go on.

On Sat, Dec 27, 2014 at 5:14 PM, Alexandru Stanciu <notifications@github.com

**Comment by ducu** [comment]
Ok done, here's the diff: https://github.com/ducu/rq-dashboard/compare/nvie:master...master

It's a sort of a hack, and it's not very efficient.. You can take a look and see if it's worth, let me know if you want a pull request. The problem is that `rq` doesn't have a proper redis structure to get finished (and started) jobs, so I had to get all available jobs by keys and filter them by queue and status on the client. It's slower but it works.

Basically I extended the `Queue` class here in `rq-dashboard`.
https://github.com/ducu/rq-dashboard/blob/master/rq_dashboard/queue.py

The job list per queue now contains started and finished jobs (for as long as they live) besides the queued ones. The result for the finished jobs is displayed just like the exception for failed jobs. 
I find it quite useful because I can see the real time results from all the workers inside the dashboard.

![screen shot 2014-12-28 at 21 48 24](https://cloud.githubusercontent.com/assets/104093/5564758/9bf5f668-8edb-11e4-8d86-68f01be91755.png)

**Comment by davibe** [comment]
https://github.com/nvie/rq/blob/master/rq/registry.py#L92
Does this relate ?

**Comment by ducu** [comment]
It seems so, I'll look into it, have to see how to activate these registries because I did't see these keys in redis while using rq. Thanks

—

**Comment by ducu** [comment]
Ok got it, I was working with rq release 0.4.6 which doesn't have the registries.

I can adapt to work with the master branch if @nvie would consider a pull request with this. The feature can be further improved of course, it would be nice to have job filters by status (queued, started, finished), and even ordering by time. Maybe we can create a separate branch for it. 

Please let me know, cheers.

**Comment by honi** [comment]
It would be great to have this feature +1

**Comment by joostdevries** [comment]
Recently the idea of an `rq.runtime` module was mentioned (nvie/rq#517). This might be a very nice use-case for that as well.

**Comment by tcorbettclark** [comment]
I'm thinking of first factoring out an RQ status API (`rq_status.py`) from the Flask REST API (`blueprint.py`). This will separate Flask, REST API, and pagination concerns from RQ interactions. In addition to being cleaner, it will also make it easier to track changes and improvements to the way RQ status is obtained.

Then we can add in the above feature.

**Comment by classner** [comment]
+1! Would be very handy to have!

**Comment by lvieirajr** [comment]
+1 would be a great feature

**Comment by davibe** [comment]
@tcorbettclark are you working on this ?.anybody else ?

@nvie which structure in `rq` are the correct ones to track currently executing job and done jobs ?
Does rq code need to be touched for this ?

**Comment by tcorbettclark** [comment]
Hi Davide.

Sorry, no I'm not working on this. May be able to get back to it after
Christmas now.

**Comment by rontendo-jp** [comment]
Seems like this thread is stalled...

@ducu, does your master still have the finished job showing in the GUI?
I mean I tried look into (https://github.com/ducu/rq-dashboard/blob/master/rq_dashboard/queue.py) but it is showing a 404 error now....

I still need the rq-dashboard that shows jobs that are completed.... willing to take it from a forked version.... :)

**Comment by ducu** [comment]
Hey my fork is gone, this repo got moved to my account but I didn't merge
what was in my fork because it was not polished enough.
I'll see what I can do following weeks but can't promise anything...

On Wed, 12 Oct 2016 at 18:05, Ron Sid notifications@github.com wrote:

Seems like this thread is stalled...

@ducu https://github.com/ducu, does your master still have the finished
job showing in the GUI?
I mean I tried look into (
https://github.com/ducu/rq-dashboard/blob/master/rq_dashboard/queue.py) but
it is showing a 404 error now....

I still need the rq-dashboard that shows jobs that are completed....
willing to take it from a forked version.... :)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/ducu/rq-dashboard/issues/69#issuecomment-253258338,
or mute
the thread

**Comment by nicbou** [comment]
Any update on this feature? The other ticket about that feature was closed without any resolution.

**Comment by willgdjones** [comment]
+ 1 Would be great!

**Comment by harlowja** [comment]
+1

**Comment by cw1427** [comment]
is this request feature ready? It indeed is really helpful.

**Comment by coolhacker** [comment]
https://github.com/Parallels/rq-dashboard/issues/283

**Comment by kennysong** [comment]
Looks like this issue was prematurely closed. The PR is not merged and there's still no way to see successful jobs.

**Comment by dmangla3** [comment]
+1 . Important feature.

**Comment by HarryAnkers** [comment]
+1
