### ISSUE TITLE
Dashboard Page Load Issue

### ISSUE THREAD

**Issue by jredd** [Parallels/rq-dashboard#93]
I have the dashbaord and everything up and running under supervisor and it works great. The issue is, after a few days of running when I go to the dashboard end point, the page doesn't load, doesn't time out, and just sits there with the browsers info message at the bottom saying waiting on end point. I've hopped onto the box and did the command line queries and all the workers are up and running just fine. Supervisor even says everything is working dandy as well. It seems the dashboard is just tanking and nothing else is really having an issue.

**Comment by vdernis** [comment]
I have the same issue and have not had time yet to dig into it.

**Comment by jredd** [comment]
Any idea on how to fix this?

**Comment by yunesj** [comment]
I had the same issue. I was getting the problem after just a few hours, but haven't gotten the problem since greatly increasing the --interval.

After a few minutes:

```
netstat -peanut | grep 9181 | grep TIME_WAIT | wc -l
156
```

My guess is that rq-dashboard (or the client browser code) isn't closing connections or isn't closing them fast enough, and it is hitting either the open files limit (mine was set to a paltry 1024) or some tcp connection limit.

**Comment by eoranged** [comment]
This might be a consequence of dashboard hitting the server with a constant interval without waiting of response completion. Now as It is fixed, closing the issue.
